# Generated by Django 5.2.2 on 2026-03-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_utilisateur_nombre_projet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='nom',
            field=models.CharField(max_length=200, blank=True, null=True),
        ),
    ]
