# Generated by Django 5.2.2 on 2026-03-27 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_utilisateur_nom_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='nom',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
