# Generated by Django 5.2.2 on 2026-03-27 14:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0016_alter_categorie_projet_image_categorie_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='projet',
            index=models.Index(fields=['titre_projet', 'date_creation'], name='idx_titre_date_creation'),
        ),
        migrations.AddIndex(
            model_name='projet',
            index=models.Index(fields=['titre_projet'], name='idx_titre'),
        ),
        migrations.AddIndex(
            model_name='visuel',
            index=models.Index(fields=['titre_visuel', 'date_creation'], name='idx_titre_date_creation_visuel'),
        ),
        migrations.AddIndex(
            model_name='visuel',
            index=models.Index(fields=['titre_visuel'], name='idx_titre_visuel'),
        ),
    ]
